project:
  type: website

website:
  title: "Crakt"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: posts/index.md
        text: Posts

format:
  html:
    theme:
      # See: https://quarto.org/docs/output-formats/html-themes.html
      light: default
      dark: cyborg
    css: styles.css
    toc: true
