project:
  type: website

website:
  title: "Crakt"
  navbar:
    logo: https://avatars.githubusercontent.com/u/30079974?s=48&v=4
    logo-href: https://github.com/RoarkCats
    left:
      - href: index.md
        text: Home
      - href: posts/index.md
        text: Posts

format:
  html:
    theme:
      # See: https://quarto.org/docs/output-formats/html-themes.html
      light: default
      dark: cyborg
    css: styles.css
    toc: true
